"""initial migration

Revision ID: c091a407abc1
Revises: 
Create Date: 2023-04-10 20:19:37.677870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c091a407abc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['characteristic.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_detail_detail_id'), ['detail_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_detail_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_detail_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_detail_detail_id'))

    op.drop_table('product_detail')
    # ### end Alembic commands ###
