"""empty message

Revision ID: ddcc5578ae0b
Revises: c091a407abc1
Create Date: 2023-04-17 22:45:07.617282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcc5578ae0b'
down_revision = 'c091a407abc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_brand_slug'), ['slug'], unique=False)

    with op.batch_alter_table('goods_in_cart', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods_in_cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
